spring:
  profiles:
    active: java-serializer
  datasource:
    url: "jdbc:h2:mem:gymmaster3000db"
    driver-class-name: "org.h2.Driver"
    username: "sa"
    password:
  h2:
    console:
      enabled: true # app will be available on http://localhost:8080/h2-console
  jpa:
    hibernate:
      spring.jpa.database-platform: 'org.hibernate.dialect.H2Dialect'
      ddl-auto: create-drop
      show-sql: true
      format_sql: true
      use_sql_comments: true
logging:
  level:
    org:
     springframework:
       web:
         filter:
           CommonsRequestLoggingFilter: 'DEBUG'
  root: 'INFO'
  acmecorp.gymmaster3000: 'DEBUG'
server:
  error:
    include-binding-errors: 'always'
    include-message: 'always'